version: '3'

services:
  app:
    container_name: nodejs_boilerplate_be
    build: .
    entrypoint: >
      sh -c "cd /app && npm run migrate:up && nodemon index.js"
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
    networks:
      - nodejs_boilerplate
    volumes:
      - ./:/app
      - /app/node_modules

  mariadb:
    container_name: nodejs_boilerplate_mariadb
    image: mariadb:latest
    ports:
      - '3310:3306'
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - nodejs_boilerplate
    volumes:
      - mariadb_nodejs_boilerplate:/var/lib/mysql

  phpmyadmin:
    container_name: nodejs_boilerplate_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '81:80'
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - nodejs_boilerplate

networks:
  nodejs_boilerplate:
    driver: bridge

volumes:
  mariadb_nodejs_boilerplate:
